version: "3.8"

services:
  restapi:
    build:
      context: .
      dockerfile: src/time_series_classification/deployment/Dockerfile.restapi
    ports:
      - "8000:8000"

  streamlit:
    build:
      context: .
      dockerfile: src/time_series_classification/streamlit_app/Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - restapi
