
FROM python:3.11-slim

WORKDIR /app
COPY ./ ./


RUN pip install mlflow fastapi pydantic tensorflow scikeras uvicorn


EXPOSE 8000


CMD ["python", "src/time_series_classification/deployment/RestAPI.py"]
