channels:
- conda-forge
dependencies:
- python=3.12.1
- pip<=24.0
- pip:
  - mlflow==2.16.2
  - attrs==24.2.0
  - cloudpickle==3.0.0
  - dill==0.3.8
  - huggingface-hub==0.24.6
  - jaraco-collections==5.1.0
  - numpy==1.26.4
  - pandas==2.0.3
  - psutil==5.9.0
  - scikeras==0.13.0
  - scikit-learn==1.4.2
  - scipy==1.12.0
  - tblib==3.0.0
  - tensorflow-intel==2.16.1
name: mlflow-env
