name: CI

on: [push, pull_request]

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest flake8 bandit safety

      - name: Run linter
        run: flake8 .

      - name: Run security checks
        run: |
          bandit -r .
          safety check

      - name: Test with pytest
        run: pytest

      - name: Run SAST
        uses: github/codeql-action/analyze@v2
